theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Smart Fusion
description: Providing accurate loacalization and orientation using UWB and IMU sensor fusion to allowing for more intuitive smart home device control.
