remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have on

theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Smart Fusion
description: Providing accurate loacalization and orientation estimations using UWB and IMU sensor fusion, allowing for more intuitive smart home device management.

github:
  zip_url: https://github.com/SimonSchirber/Ultra-Wide-Band-M202/zipball/master/
  tar_url: https://github.com/SimonSchirber/Ultra-Wide-Band-M202/tarball/master
  repository_url: https://github.com/SimonSchirber/Ultra-Wide-Band-M202